install: true
language: java
sudo: false
script:
- ./gradlew clean build jacocoTestReport
after_success:
- ./gradlew coveralls
cache:
  directories:
  - $HOME/.gradle
jdk:
- oraclejdk8
env:
  global:
  - TERM=dumb
  - CI_NAME=travis-ci
  - secure: n8denx33yek5SzVMsXQn2dot/EZUlZbH0Pz3OMbQ2ZoJK6sWD71MSs9xmEjhZJk3htbPwcWTnH0EJ0bsBcPguEA4bBWjXMS58yj+9AwcLkxMonVniXaYOjzxvuS5ALmrfatyYtZKlY/3hlhZOHcyGZou4HIft6Y+as4pSUs2WYnD7rr7REM5++T4bS2Xm2cyym42gMW6VDCCrSi8k31t/rypcvF3oitcXbKZ9t0K315fVX4r5/nGrhKQIz7qXnPyGi989DgSlTDdJ8hf8XJ6X8DTX/cNyE66CKit0cOJoGyHKDpL1jYS2UzFXF7tq4YFsRHq/QBsEnpzyVwsmFljvMqfTCh9MwHv3jELhpSUC+cBNMUkvq/+WQy7duRqHJdBpveRCUgT/mEYU8hNHRCpQdbLsK1TWSyauclBY6rhQGykqRDPZdKmBKQuoeMgMR0WzJaKzByDFvEhPwyYKM5wCmAIByin3JMcQD0vWJoaVo1MDkootuDUoQMmm+XOab4fKi5gq0NCyl9B57tUWD2t8+VCo0xyPst478tMZ9bN1VoPmYTdqy5yADtAOoQzs3Qq1/26uf+ESgR9puxr5GOwgbawiJlIM8q+2/Gn0SQZvJ/6496fVQY+nINPZMr0iYW12KXNiRbqM/COJlk/EiqY8ZdTM2p+STrw0BrEGCU1myk=
